services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:4321"
    restart: unless-stopped
    container_name: mate-tinta-disparate
    networks:
      - proxy-network
    volumes:
      - .:/app

networks:
  proxy-network:
    external: true
