services:
  web:
    # Ahora descargamos la imagen construida por GitHub Actions
    image: ghcr.io/reimonlp/mate.tinta.disparate:latest
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: mate-tinta-disparate
    networks:
      - proxy-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - DOCKER_API_VERSION=1.40
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Revisa actualizaciones de 'mate-tinta-disparate' cada 300 segundos (5 minutos)
    command: --interval 300 mate-tinta-disparate
    restart: unless-stopped

networks:
  proxy-network:
    external: true
