version: '3.8'

services:
  web:
    # Ahora descargamos la imagen construida por GitHub Actions
    image: ghcr.io/reimonlp/mate.tinta.disparate:latest
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: mate-tinta-prod

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Revisa actualizaciones de 'mate-tinta-prod' cada 300 segundos (5 minutos)
    command: --interval 300 mate-tinta-prod
    restart: unless-stopped
