server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Deshabilitar cache para desarrollo
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires off;
        
        # Dejar que Nginx envíe el Last-Modified real del archivo
        # Forzamos a que no se use validación por cache
        if_modified_since off;
        
        try_files $uri $uri/ =404;
    }
}
